InnovativeOnlineIndustries/Industrial-Foregoing

src/main/java/com/buuz135/industrial/utils/strawhandlers/PotionStrawHandler.java

Fix straw being retarded

---

src/main/java/com/buuz135/industrial/tile/block/MaterialStoneWorkFactoryBlock.java

No more "grindd" and crafting "the."

Fixed a Small Typo

---

src/main/resources/assets/industrialforegoing/lang/pt_BR.lang

Hello!
Today I noticed you added a machine called "Plant Interactor". Well... This is a very hard name to translate.
hehehe... Because, what it does is VERY similar to what the Plant Recolector does... So... Basicly, their names, in my language, will be the same... They take plants and put them into their inventories... This is why is so dificult to create a diferent name for something that, basicly, makes almost the same thing...
Well... This is just a comment. =)

Added Plant Interactor to pt-BR.lang

---

src/main/resources/assets/industrialforegoing/lang/pt_BR.lang

Fixed Energy Field Tooltip (pt-BR.lang)

---

src/main/resources/assets/industrialforegoing/lang/pt_BR.lang

Hello!
Thank you!
And sorry, if I'm intruding too much on the project.
Bye, bye! xD

Added Translated book categories and Transf Addons (pt-BR)

---

src/main/java/com/buuz135/industrial/tile/magic/EnchantmentExtractorTile.java

https://github.com/Buuz135/Industrial-Foregoing/commit/64139a9a5cdff4dc91b0b20a6827f3f4ad30896d#r30740289

Fixed item repair cost

---

src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java

fixed custom farmland compat

---

src/main/java/com/buuz135/industrial/block/generator/tile/PitifulGeneratorTile.java
src/main/java/com/buuz135/industrial/block/resourceproduction/tile/DyeMixerTile.java
src/main/java/com/buuz135/industrial/block/tile/TileEntityLabel.java
src/main/java/com/buuz135/industrial/block/transport/conveyor/ConveyorBouncingUpgrade.java
src/main/java/com/buuz135/industrial/item/MeatFeederItem.java
src/main/java/com/buuz135/industrial/item/infinity/ItemInfinityDrill.java

This fixes  #708 and Adresses reported issues with IF not respecting System Locales with Formatting.
Disclaimer:
This is not fully tested since a change needs to be done to Titanium to support the refactored class name in Forge of ModConfig.ConfigReloaded!

Fix Fuel Burn-Time getter, Fix Locale issues

---

src/main/java/com/buuz135/industrial/proxy/client/event/IFClientEvents.java

Hopefully fixed #688 "UnsupportedOperationException: No bounds for empty shape"

Hopefully fixed #688

---

src/main/resources/data/forge/tags/fluids/biofuel.json
src/main/resources/data/forge/tags/fluids/essence.json
src/main/resources/data/forge/tags/fluids/latex.json
src/main/resources/data/forge/tags/fluids/meat.json
src/main/resources/data/forge/tags/fluids/milk.json
src/main/resources/data/forge/tags/fluids/pink_slime.json
src/main/resources/data/forge/tags/fluids/sewage.json
src/main/resources/data/forge/tags/fluids/sludge.json

Add fluid tags to be compatible with other mods.

Add fluid tags

---

src/main/java/com/buuz135/industrial/item/MobImprisonmentToolItem.java
src/main/java/com/buuz135/industrial/utils/IndustrialTags.java
src/main/resources/data/industrialforegoing/tags/entity_types/mob_imprisonment_tool_blacklist.json

I've implemented the Mob Imprisonment Tool blacklist using an entity type tag to allow other mods to blacklist entities

Implemented Mob Imprisonment Tool blacklist

---

src/main/java/com/buuz135/industrial/utils/MovementUtils.java

Changed the conveyor moving measurements so it measures the entities double position instead of a block pos int
closes #821

Fixed Conveyor belts pushing items to the side not the middle

---

src/main/java/com/buuz135/industrial/block/core/tile/FluidExtractorTile.java

fluid extractor no longer uses power when its tank is full.
closes #822

Fixed fluid extractor from using power when tank is full

---

src/main/java/com/buuz135/industrial/item/infinity/item/ItemInfinityBackpack.java

Item pickup events now check vs the contents of multiple infinity backpacks in the player's inventory.

Item pickup events now check vs the contents of multiple infinity backpacks in the player's inventory.

---

src/main/resources/assets/industrialforegoing/lang/en_us.json

This is for The One Probe/HWYLA/Jade compatibility
This PR fixes the localization issue seen at the top:

Added localization for Infinity Nuke entity

---

src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/MobDuplicatorTile.java
src/main/java/com/buuz135/industrial/item/MobImprisonmentToolItem.java
src/main/java/com/buuz135/industrial/utils/IndustrialTags.java
src/main/resources/data/industrialforegoing/tags/entity_types/mob_duplicator_blacklist.json

Would close #1183 on Foregoing's part, as Mekanism could register the Robit under the new blacklist tag.

Separate blacklist only for the mob duplicator

---

src/generated/resources/data/industrialforegoing/recipes/laser_drill_ore/certus_quartz.json

Add AE2's Certus quartz ore to Laser Drill recipes

Add certus quartz to Laser Drill recipes

---

src/main/java/com/buuz135/industrial/block/resourceproduction/tile/FluidLaserBaseTile.java

Fix for fluid laser base not detecting the biome it's in correctly. Fixes #1313

fix for fluid laser base not detecting biome correctly

---

src/main/java/com/buuz135/industrial/item/infinity/InfinityEnergyStorage.java

Corrected getMaxEnergyStored() return value of InfinityEnergyStorage. Fixes issue #1213.

Corrected getMaxEnergyStored() return value of InfinityEnergyStorage.

---

src/main/java/com/buuz135/industrial/block/generator/mycelial/FireworkGeneratorType.java

Backport of https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/pull/1428
* Fix FireworkGeneratorCategory not showing up in JEI by reworking calculate(ItemStack stack) and getRecipes() in FireworkGeneratorType
* Added 3 recipes to the FireworkGeneratorType

[1.18] Fix FireworkGeneratorCategory not showing up in JEI

---

build.gradle
gradle.properties
src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/MobCrusherTile.java
src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantSowerTile.java
src/main/java/com/buuz135/industrial/block/resourceproduction/tile/MechanicalDirtTile.java
src/main/java/com/buuz135/industrial/block/resourceproduction/tile/PotionBrewerTile.java
src/main/java/com/buuz135/industrial/item/infinity/ItemInfinity.java
src/main/java/com/buuz135/industrial/mixin/IBushBlockMixin.java
src/main/java/com/buuz135/industrial/utils/StrawUtils.java
src/main/resources/META-INF/mixins.json
src/main/resources/META-INF/neoforge.mods.toml

Resolves #1484, #1479, #1476, #1472
This PR fixes few of the bugs recently reported for 1.21.1 😄 Fixes included were small, so this PR contains 4 different issues.
There are few issues that will require a bit more work, and posibly changes to Titanium, so those will be included in another PR.

A bunch of Bug Fixes for 1.21
