InnovativeOnlineIndustries/Industrial-Foregoing

src/main/java/com/buuz135/industrial/tile/mob/VillagerTradeExchangerTile.java
We currently only check the first item to buy, so allowing these kinds of
trades means that players are only having to pay one of the two items.
Long-term, we plan to add a second buying slot to the exchanger, but until
then, prevent this sort of trade.
=> Prevent using trades with 2 items to buy in the trade exchanger (#77)

build.gradle, src/main/java/com/buuz135/industrial/tile/agriculture/AnimalResourceHarvesterTile.java
Before this fix, a Fake Player would milk a Moo Fluid cow with a bucket, resetting the cooldown. But, if there was a different fluid already in the Rancher's tank, the bucket would get trashed. This means all Fluid Cows in the affected area would get their cooldowns reset, but only the first cow would produce fluid. This change corrects that. 
Animal Rancher now checks if the animal is a Fluid Cow from moofluids. If the cow has a different fluid than what is in the tank, it skips it. This allows a pen full of Fluid Cows to be "milked" in rapid succession. Fixes issue #441 . Also confirmed the rancher still behaves as-expected with normal cows if MooFluids is not installed.
https://imgur.com/T1G82M8
=> Animal Rancher works with Fluid Cows. Fixes Issue #441

src/main/java/com/buuz135/industrial/module/ModuleCore.java
Forgive me if this fails to compile, as I've done it (horribly) from the browser in a rush. 
This fixes IF milk buckets used in recipes having the bucket deleted when used in recipes rather than returned as per usual. Item.containerItem is actually defined through properties rather than through a function, and the default BucketItem does (obviously) no longer specify this.
=> Specify container item for MilkBucket replacement

src/main/java/com/buuz135/industrial/proxy/client/event/IFClientEvents.java
The infinity drill was crashing the client when looking at water or lava.
Additionally, the height of the boxes being rendered in the same function was slightly off, based on the eye height of the player. A little bit of other code was cleaned up in the same file to remove deprecated method calls and use the static instead of instance method for drawSelectionBoundingBox.
See: https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/646
=> Fixed client crash + height of rendered boxes when using drill.

build.gradle, src/main/java/com/buuz135/industrial/utils/BlockUtils.java
Now this block check based on tag system instead of material.
Also titanium version has been incremented. Because in 1.15.2 Forge has some renamed classes
=> Change BlockUtils.isLog(). Fix for #661, #700

src/main/java/com/buuz135/industrial/block/generator/tile/BiofuelGeneratorTile.java
BioFuelGenerator now checks if it is full of power before it uses biofuel.
closes #830
=> Fixed biofuelgenerator from using fuel when its full of energy

build.gradle
Couldn't build the jar because in 3.2.0 of Titanium in the EnergyStorageComponent class the componentHarness attribute was private but in version 3.2.1 it's protected
=> build.gradle fixed to work with Titanium 3.2.1

src/generated/resources/data/industrialforegoing/recipes/laser_drill_ore/osmium.json, src/main/java/com/buuz135/industrial/recipe/LaserDrillOreRecipe.java
I just noticed that it wasn't generating when I ran out of it in Valhelsia 3. Whoops.
For those unaware, osmium is a critical ore used in Mekanism for the production of circuits, which are used to create practically all machines. Having it just as rare as tin lines up with about what Mekanism expects balance-wise.
Disclaimer: This commit is untested since I don't have a Forge workspace set up at the moment, but it's such a simple change I don't anticipate it'll cause any issues \</famouslastwords\>.
=> 1.16: Add Osmium to Laser Drill recipes

src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/MobCrusherTile.java
Fixes #899 
Fixes #898
Tested in a test world. Does not kill child AnimalEntities but does kill adult AnimalEntities (as it's supposed to). 
Fixes the Rats issue because Rats are considered AnimalEntities.
IMO the Mob Crusher SHOULD kill child mobs and the real issue is that the Loot Table is being populated with adult mob drops for child mobs. I understand however that skipping child mobs is a much easier fix than that however.
=> Fix Mob Crusher not killing adult AnimalEntities

src/main/java/com/buuz135/industrial/IndustrialForegoing.java, src/main/java/com/buuz135/industrial/proxy/client/ClientProxy.java
ModelLoader.addSpecialModel must be called at the proper time - during or before the ModelRegistryEvent, so that the game is able to bake and cache the model. 
ClientProxy.run is called during FMLClientSetupEvent, which is fired AFTER all of the registry events, including ModelRegistryEvent, so previously the model was not baked in time.   
There is a race condition related to this, however, that may allow it to bake before the models are cached. This is non-deterministic, however.
I moved the code to a dedicated unsafeRunWhenOn block, using the EventManager system to subscribe the ModelLoader line to the proper event, so that it may run consistently.   
This fixes the ears reward, for me and possibly everyone else having issues with it.
I moved the nearby line to an unsafeRunWhenOn …
=> Fix Ears Reward

build.gradle, src/main/java/com/buuz135/industrial/plugin/AstralSorceryPlugin.java
Added a FeaturePlugin for Astral Sorcery to allow the Infinity Drill to mine marble and black marble. Tested with AstralSorcery-1.16.4-1.13.9
This adds a compile-time dependency for AstralSorcery-1.16.4-1.13.9 from cursemaven.com
Replacing the materials array feels a bit hacky; not sure if this is the desired approach to implementing this.
=> Add Astral Sorcery plugin to allow Infinity Drill to mine Marble (#1008)

src/main/java/com/buuz135/industrial/proxy/client/ClientProxy.java
When calling `BlockRenderDispatcher#renderBlock` it calls the function `IBlockColor#getColor` with `null` for both the world and blockpos parameters.
The registered `IBlockColor` instance currently results in a null pointer exception in this case.
With my mod Entangled, I try rendering other blocks inside the entangled block using `BlockRenderDispatcher#renderBlock`.
Thus running into the issue.
I propose adding a null check for the mentioned parameters as they are annotated with `@Nullable`.
=> Add a null check for IBlockColor parameters

src/main/java/com/buuz135/industrial/block/transportstorage/tile/BlackHoleTankTile.java, src/main/java/com/buuz135/industrial/fluid/OreFluidInstance.java, src/main/java/com/buuz135/industrial/fluid/OreTitaniumFluidAttributes.java, src/main/java/com/buuz135/industrial/item/OreBucketItem.java, src/main/java/com/buuz135/industrial/proxy/client/ClientProxy.java, src/main/java/com/buuz135/industrial/utils/ColorUtils.java, src/main/java/com/buuz135/industrial/utils/FluidUtils.java, src/main/java/com/buuz135/industrial/utils/ItemStackUtils.java
- Black Hole Tanks would previously not correctly render certain fluids that had translucent non-grayscale textures, and would not render either a bucket or a quantity for fluids that have no filled bucket. I fixed the color code, and also made it use an empty bucket when there is no bucket.
- Ore Meat would lose the NBT tag when put in a bucket [in all contexts, including filling a bucket in IF itself, in other mods, or the bucket displayed on a black hole tank]. Fixing this required a custom bucket item and fluid handler class, since Forge provides no support for NBT with standard bucket items.
Implementation notes: This patch does not prevent NBT-less ore meat from being created in all contexts, and it doesn't prevent problems caused by trying to process NBT-less ore meat. There's no …
=> Fluid fixes [black hole tank rendering and ore meat buckets]

src/main/java/com/buuz135/industrial/block/transportstorage/tile/BlackHoleUnitTile.java
This fixes the issue described in #1093.
With the Void Items enabled, the BHU would cause the amount to overflow, as once it is at its max, void would still attempt to insert more in.
If there was a better way to prevent this, I'm happy to refactor the fix.
=> Voided Black Hole Unit overflowing once at max size

src/main/java/com/buuz135/industrial/block/agriculturehusbandry/tile/PlantGathererTile.java, src/main/java/com/buuz135/industrial/block/resourceproduction/tile/BlockBreakerTile.java, src/main/java/com/buuz135/industrial/block/resourceproduction/tile/BlockPlacerTile.java, src/main/java/com/buuz135/industrial/block/resourceproduction/tile/FluidCollectorTile.java, src/main/java/com/buuz135/industrial/block/resourceproduction/tile/FluidPlacerTile.java, src/main/java/com/buuz135/industrial/recipe/FluidExtractorRecipe.java, src/main/java/com/buuz135/industrial/utils/BlockUtils.java
This pull request introduces two changes to address some performance issues discovered in recent profiles of the official Enigmatica 6 server (see each individual issue descriptions for an example profile)
1. Avoid calling `getPointedBlockPos()` excessively in tile entities where possible (https://spark.lucko.me/jzsDC7KbEE):
Since `getPointedBlockPos()` **shouldn't** change over the course of a single work tick and calling it should be considered an expensive operation (mostly due to the underlying call to `BlockUtils#getBlockPosInAABB`, I've chosen to just cache it for the duration of the work tick where this wasn't the case already. The profile specifically shows the Plant Gatherer tiles causing a fair bit of tick lag, which is probably due to the fact that `getPointedBlockPos()` was …
=> Two small potential performance boosts

src/main/java/com/buuz135/industrial/IndustrialForegoing.java
Various types of exceptions will be thrown when trying to open a connection, not only MalformedURLException.
=> Fix crash on network error

src/main/java/com/buuz135/industrial/item/infinity/ItemInfinity.java
ItemInfinity overrides getDurabilityForDisplay and getRGBDurabilityForDisplay and implementations for both use the client-only check `Screen.hasShiftdown()`. This change modifies these methods to use the default (i.e. shift is not pressed) behaviour when the methods are called server-side.
I encountered this issue when playing with Valhelsia 3 and encountered it using ComputerCraft. A quick search brought a similar issue with the same cause using "MineColonies for ComputerCraft". (https://github.com/uecasm/colony4cc/issues/6)
=> Fixed ItemInfinity using client-only functionality server-side

src/generated/resources/data/industrialforegoing/recipes/laser_drill_ore/raw_materials/cobalt.json, src/main/java/com/buuz135/industrial/block/resourceproduction/tile/OreLaserBaseTile.java
IF was not honoring the mod priority list for returned items.  The actual behavior was to return something farther down on the list o not on the list at all.  Also fixed an incorrect tag in the Raw Cobalt recipe.
Fix bug which made ore laser not honor Titaniums mod preference list
Fix tags in Raw Cobalt recipe
=> Fix bug which made ore laser not honor Titaniums mod preference list

src/main/java/com/buuz135/industrial/proxy/block/filter/ItemStackFilter.java
Fix issue between Mob Imprisonment tool not getting registered correctly when attempting to be matched by a filter.
=> Fix issue with Mob Imprisonment Tool with filter matching

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/buuz135/industrial/block/resourceproduction/tile/OreLaserBaseTile.java
Fixed an incorrect `ResourceLocation` lookup, which produced nulls and caused `getValidRarity` to fail for "heavily whitelisted" items.
This should fix https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1305 and similar issues.
Also, bumped gradle version and added Mekanism for easier testing.
=> Fix for whilelist-only ores (including Ancient Debris) not being mined by the ore laser

src/main/java/com/buuz135/industrial/IndustrialForegoing.java
DimensionType could be the same for modded worlds, fix #1303
=> Using hashCode method instead of DimensionType

src/generated/resources/data/industrialforegoing/recipes/laser_drill_ore/ores/cinnabar.json, src/generated/resources/data/industrialforegoing/recipes/laser_drill_ore/ores/yellorite.json, src/main/java/com/buuz135/industrial/recipe/LaserDrillOreRecipe.java
Added yellorite ore as a laser drill result. 
Extreme Reactors uses forge:ores/yellorite.
=> Laserdrill compat to Extreme Reactors

src/main/java/com/buuz135/industrial/block/generator/mycelial/FireworkGeneratorType.java
* Fix FireworkGeneratorCategory not showing up in JEI by reworking calculate(ItemStack stack) and getRecipes() in FireworkGeneratorType
* Added 3 recipes to the FireworkGeneratorType
* Fix a bug where inserting 1 firework would consume firework before power was generated in FireworkGenerator
=> [1.20] Fix FireworkGeneratorCategory not showing up in JEI

src/main/java/com/buuz135/industrial/block/transportstorage/tile/BlackHoleUnitTile.java, src/main/java/com/buuz135/industrial/capability/BLHBlockItemHandlerItemStack.java
Fix a bug where Black Hole Units could accept arbitrary items and transmute the original items when the last insert operation had a size of 128 or larger.
Fixes #1399.
=> [1.20] Fix bug where Black Hole Units could transmute items

src/main/java/com/buuz135/industrial/plugin/jei/subtype/AddonSubtypeInterpreter.java, src/main/java/com/buuz135/industrial/plugin/jei/subtype/InfinitySubtypeInterpreter.java, src/main/java/com/buuz135/industrial/utils/CraftingUtils.java, src/main/resources/META-INF/neoforge.mods.toml
Happy [Modtoberfest](https://modtoberfest.com/)!
Tested against a big pack (ATM10)
Before (`industrialforegoing-1.21-3.6.13`): 
`Registering recipes: industrialforegoing:default took 865.1 milliseconds`
After: 
`Registering recipes: industrialforegoing:default took 166.8 milliseconds`
This builds a cache of 2x2 and 3x3 recipes where all ingredients are identical.
Building the cache is expensive but checking against them repeatedly pays off later.
=> Optimize JEI startup time

src/main/resources/data/industrialforegoing/recipe/manual.json
Currently when the mod is loaded without Patchouli the Guide recipe errors out because it expects the patchouli guide_book to exist. This PR adds the item_exists condition to ignore the recipe if it's missing.
This PR does the following:
* Add `neoforge:item_exists` condition to the guide recipe
Happy ModToberFest
=> Add `item_exists` condition to the guide recipe

src/main/java/com/buuz135/industrial/api/transporter/FilteredTransporterType.java, src/main/java/com/buuz135/industrial/block/transportstorage/transporter/TransporterFluidType.java, src/main/java/com/buuz135/industrial/block/transportstorage/transporter/TransporterItemType.java, src/main/java/com/buuz135/industrial/block/transportstorage/transporter/TransporterWorldType.java, src/main/java/com/buuz135/industrial/block/transportstorage/transporter/filter/FluidFilter.java, src/main/java/com/buuz135/industrial/block/transportstorage/transporter/filter/ItemFilter.java, src/main/java/com/buuz135/industrial/gui/component/custom/RegulatorFilterGuiComponent.java, src/main/java/com/buuz135/industrial/proxy/block/filter/RegulatorFilter.java
This PR reworks the Transporter Logic, fixing few bugs and adding new features!
It also slightly buffs all of the transporters.
- Transporters now work in Regulate Mode on the Extraction side!
They will leave in the storage the amount of items specified in the filter.
- Regulate Mode affects only whitelist mode - it's ignored in blacklist mode.
- Efficiency is being calculated now with use of `Math.ceil(int)` instead of direct cast to `int`, fixing an issue that max transporters were able to handle "only" 63 of stuff per work cycle. (They now handle at max 64/t)
- Entire Filtering logic was moved to the RegulatorFilter class, including Whitelist and Regulate mode.
This makes it simpler to implement filters and later on - logic in the transporters, as all checks are handled by the filter. …
=> Rework Transporter Logic

src/main/java/com/buuz135/industrial/item/MobImprisonmentToolItem.java
DISCARDED is a more appropriate way to discard a mob instead of KILLED if it's not being killed and just being removed from the world. Helps with mods that perform certain actions on mobs if their removal reason is KILLED to not misbehave with the mob imprisonment tool.
=> Entity.RemovalReason change in MobImprisonmentToolItem.java

src/main/java/com/buuz135/industrial/block/core/tile/FluidExtractorTile.java, src/main/java/com/buuz135/industrial/plugin/emi/recipe/FluidExtractorEmiRecipe.java, src/main/java/com/buuz135/industrial/plugin/jei/category/FluidExtractorCategory.java, src/main/java/com/buuz135/industrial/recipe/FluidExtractorRecipe.java
Fixes InnovativeOnlineIndustries/Industrial-Foregoing#1533
Test recipe:
```
{
"type": "industrialforegoing:fluid_extractor",
"breakChance": 0.01,
"defaultRecipe": false,
"input": {
"item": "minecraft:stone"
},
"output": {
"amount": 3,
"id": "minecraft:water"
},
"result": {
"Name": "minecraft:cobblestone",
"Properties": {
"axis": "y"
}
}
}
```
=> DRY up latex bonus code, make "triple" display conditional.

src/main/java/com/buuz135/industrial/block/resourceproduction/tile/PotionBrewerTile.java
Allows slot extraction from the output slots when the filter slot is empty. Fixes reliance on the "push" action for output, and allows external automation sources to extract more than one type of item.
I figured it would be more appropriate to modify this directly in the potion brewer rather than looking into [Titanium](https://github.com/InnovativeOnlineIndustries/Titanium).
=> Allow potion brewer output if no filter is specified

src/main/java/com/buuz135/industrial/proxy/client/render/MycelialReactorTESR.java, src/main/java/com/buuz135/industrial/proxy/client/render/WorkingAreaTESR.java
Fixes #1562 and https://github.com/RaphiMC/ImmediatelyFast/issues/337
While this is technically an ImmediatelyFast issue, I decided to fix it in Industrial Foregoing. The code in Industrial Foregoing isn't correct and ImmediatelyFast causes the issue to be visible. Without ImmediatelyFast the issue happens as well, but at a different place in rendering, after the chests are rendered (It doesn't really affect anything in vanilla because the Industrial Foregoing code is called pretty much last). ImmediatelyFast slightly reorders the render calls which causes the issue to be visible.
=> Change depth mask back to true after rendering

src/generated/resources/data/industrialforegoing/advancement/crusher/sand.json, src/generated/resources/data/industrialforegoing/recipe/crusher/sand.json, src/main/java/com/buuz135/industrial/recipe/CrusherRecipe.java
Fixed tags, for silicon craft, `c:sand`->`c:sands` and `c:silicons`->`c:silicon`
=> Fixed tags in sand to silicon crush recipe
